[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mercle_token = "HWuotjdXtQePUmX5WCzPxQkZ3LiiXQ6i8AYSudgJxEts"

[programs.devnet]
mercle_token = "3SkrCb3S7ocBxLZFrSYpNqTcNvdkvFpocXtpf3dZZyCo"

[programs.mainnet]
mercle_token = "HWuotjdXtQePUmX5WCzPxQkZ3LiiXQ6i8AYSudgJxEts"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
