[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
riyal_contract = "DUALvp1DCViwVuWYPF66uPcdwiGXXLSW1pPXcAei3ihK"

[programs.devnet]
riyal_contract = "DUALvp1DCViwVuWYPF66uPcdwiGXXLSW1pPXcAei3ihK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
