[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mercle_token = "2XWNXNwRdT9rfKUjsmtwi5St4yaLNDKoHiKiASyn3rLZ"

[programs.devnet]
mercle_token = "2XWNXNwRdT9rfKUjsmtwi5St4yaLNDKoHiKiASyn3rLZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
